ALTER TABLE listings ADD COLUMN city TEXT;

ALTER TABLE listings ENABLE ROW LEVEL SECURITY;

CREATE POLICY select_all ON listings FOR SELECT USING (true);
CREATE POLICY insert_all ON listings FOR INSERT WITH CHECK (true);

GRANT SELECT, INSERT ON TABLE listings TO public;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO public;
